feat(view): Add Refresh button interaction
githru/githru-vscode-ext pull request #344
Opened 2023-05-13 12:46 UTC by yewon0804

## Related issue

[view] 새로고침 버튼 인터랙션 #327 

## Result

![327](https://github.com/githru/githru-vscode-ext/assets/53112143/f713e14d-987a-4960-a08d-602365d92b65)

button component가 포함되어 있는 data-control-container의 background 변경

수정 전
![image](https://github.com/githru/githru-vscode-ext/assets/53112143/9ce9635d-2796-43dc-9278-9ecdef69a364)

수정 후
![image](https://github.com/githru/githru-vscode-ext/assets/53112143/682fecd8-7db2-4c55-b2c0-7893e07b8d0e)

## Work list

새로고침 버튼을 눌렀을 때, 새로고침이 진행중임을 알 수 있게 인터랙션을 추가합니다.

새로고침이 진행중이라면, githru 탭 중앙에 Bounce Loader가 나타납니다.

+) 스크롤을 이동했을 때
상단에 위치한 graph가 data-control-container에 가려져 보이지 않고,
가려졌을 때 자칫 현재 상태가 가려져 있는 상태인지 그냥 그래프가 나타나지 않은 것인지 분간에 어려움이 발생할 수 있을 것 같아 수정하였습니다.
- background color 삭제
- backdrop-filter: blur 추가

2023-05-13 12:49 UTC, ooooorobo commented on packages/view/src/ide/FakeIDEAdapter.ts
> +    }, 3000);
요건 테스트용으로 추가했던 건데, 원래대로 돌려주시면 좋을 것 같아요!

2023-05-13 18:45 UTC, yewon0804 commented on packages/view/src/App.tsx
> +        color="#ff8272"
- (#330) 와 연계하여, 로딩 UI의 색상도 함께 적용되도록 하거나
- githru의 테마 색상으로 고정

하는 방향으로 변경해 보는 것은 어떨까요?

2023-05-13 18:45 UTC, yewon0804 commented on packages/view/src/components/TemporalFilter/TemporalFilter.tsx
> +        color="#ff8272"
packages/view/src/App.tsx
의 리뷰 내용에서 이어집니다.

2023-05-14 01:34 UTC, ooooorobo commented on packages/view/src/App.tsx
> +    setLoading(!loading);
이 부분은 명시적으로 true 값 넣어주세요!

2023-05-14 01:42 UTC, yewon0804 commented on packages/view/src/App.tsx
> +    setLoading(!loading);
수정하였습니다! 감사합니다 😀

2023-05-14 01:47 UTC, anpaul0615 requested changes
수정요청 드린거 확인 한번 부탁드려요~

2023-05-14 01:47 UTC, anpaul0615 commented on packages/view/package.json
> +    "eslint": "^8.40.0",
feature 커밋에 eslint 버전업그레이드 와 같은게 같이 들어가면 안될것같아요.
react-spinners 추가하신거 제외하고, 나머지들(eslint, eslint-config-prettier, prettier) 는 원래대로 돌려주세요.

2023-05-14 01:47 UTC, anpaul0615 commented on packages/view/package.json
> +    "react-spinners": "^0.13.8",
react-spinners 가 devDependencies 에 들어가도 되나요? cc. @ytaek @ooooorobo

2023-05-14 02:03 UTC, yewon0804 commented on packages/view/package.json
> +    "eslint": "^8.40.0",
수정하였습니다!! 감사합니다 🥹

2023-05-14 02:07 UTC, anpaul0615 commented on packages/view/package.json
> +    "react-spinners": "^0.13.8",
죄송합니다... 제가 잘못확인했네요.
devDep 가 아니라 dep에 잘 들어가있는거 확인했습니다! (죄송..ㅠㅠ)

2023-05-14 02:24 UTC, anpaul0615 approved these changes

2023-05-14 04:41 UTC, anpaul0615 commented
todo: 새로고침 버튼을 감싸고있는 div 가 floating 되어있는 상태로 다른 UI 들을 가리고 있는 부분 수정 필요함

![image](https://github.com/githru/githru-vscode-ext/assets/8488507/7d4c6fc0-eef1-436e-bc53-56dccf071bec)

2023-05-14 04:49 UTC, anpaul0615 commented
memo: 테마색 기반 로딩UI 색상 동적 변경로직 임시원복 (추후 재적용)

2023-05-14 04:50 UTC, joonwonBaek commented
LGTM !!

2023-05-14 04:50 UTC, Yeons0110 commented on packages/view/src/App.tsx
> +    setLoading(true);
LGTM👍

2023-05-14 04:51 UTC, Yeons0110 approved these changes
LGTM😎⭐

2023-05-14 04:51 UTC, merged

2023-05-14 05:06 UTC, anpaul0615 commented
todo: package-lock.json 변경사항 반영된 내용 원복 (현재 package.json 과 버전 불일치 중)