fix(view): 상단 data-control-container가 다른 UI를 가리고 있는 부분 수정
githru/githru-vscode-ext pull request #352
Opened 2023-05-14 08:10 UTC by yewon0804

## Related issue

resolve #351

## Result

![351](https://github.com/githru/githru-vscode-ext/assets/53112143/2be29db2-977e-46d3-b93a-4f7810f425b2)

## Work list

![image](https://github.com/githru/githru-vscode-ext/assets/53112143/eac7ea98-c902-46e5-a096-e7e7ecbb8ad1)

data-control-container에 속해있던 z-index 속성을 새로고침 버튼으로 이관하였습니다.

2023-05-14 14:18 UTC, anpaul0615 requested changes

2023-05-14 14:18 UTC, anpaul0615 commented on packages/view/src/App.tsx
> +        color="var(--primary-color)"
fix 내용이랑 코드 수정사항이랑 범위가 다른듯합니다.
로딩UI 컬러코드 관련 수정사항은 이 PR 에서 제외되어야할것같아요.

2023-05-14 14:18 UTC, anpaul0615 commented on packages/view/src/components/TemporalFilter/TemporalFilter.tsx
> +        color="var(--primary-color)"
상동

2023-05-14 14:19 UTC, anpaul0615 commented on packages/view/src/components/TemporalFilter/TemporalFilter.scss
> +  z-index: 10;
👍👍

2023-05-14 14:21 UTC, anpaul0615 commented
지나가면서 했었던 말이었는데, 세심하게 수정작업 해주셔서 감사합니다 :)

다만 PR에 불필요한 커밋들이 포함되어있는게 조금 아쉽습니다.
최종적으로는 squash merge 처리를 하면 되긴하지만....  웬만하면 PR 에 나오는 커밋들을 깔끔하게 유지할 수 있도록 하는게 좋아보여요. git rebase 를 통해서 upstream, origin 간의 커밋 차이를 반영하는 방식을 사용해주세요.

2023-05-15 05:52 UTC, yewon0804 commented on packages/view/src/App.tsx
> +        color="var(--primary-color)"
관련 커밋 제외하고 새로 push --force 해보았습니다!!
로딩UI 컬러 관련해서 생각해보았는데, 해당 수정사항은 @choheejin 님 PR (#350) 에 포함되는 것은 어떨까요?

2023-05-15 05:55 UTC, yewon0804 commented
> 지나가면서 했었던 말이었는데, 세심하게 수정작업 해주셔서 감사합니다 :)
> 
> 다만 PR에 불필요한 커밋들이 포함되어있는게 조금 아쉽습니다. 최종적으로는 squash merge 처리를 하면 되긴하지만.... 웬만하면 PR 에 나오는 커밋들을 깔끔하게 유지할 수 있도록 하는게 좋아보여요. git rebase 를 통해서 upstream, origin 간의 커밋 차이를 반영하는 방식을 사용해주세요.

git rebase에 대한 개념이 부족했던 것 같습니다..
해당 PR은 추후 approve된다면 squash merge로 처리하고, 다음부터는 깔끔한 히스토리로 남길 수 있게 공부해야겠어요 🥹 크게 도움이 되었습니다 조언 감사드립니다!!

2023-06-03 01:45 UTC, ytaek approved these changes
commit log 재정비까지 해주셔서 감사합니다!!
(저도 이렇게 꼬이는 케이스가 참 많은데, 그 때마다 귀찮아서 그냥 넘겼었;;)

githru를 사용하면 이런 꼬인(?) 케이스도 잘 정리해서 보여주는 걸 시나리오에 넣는것도 좋을 것 같네요!

2023-06-03 01:45 UTC, ytaek approved these changes
commit log 재정비까지 해주셔서 감사합니다!!
(저도 이렇게 꼬이는 케이스가 참 많은데, 그 때마다 귀찮아서 그냥 넘겼었;;)

githru를 사용하면 이런 꼬인(?) 케이스도 잘 정리해서 보여주는 걸 시나리오에 넣는것도 좋을 것 같네요!

2023-06-04 09:35 UTC, merged

2023-06-04 13:41 UTC, yewon0804 commented
> commit log 재정비까지 해주셔서 감사합니다!! (저도 이렇게 꼬이는 케이스가 참 많은데, 그 때마다 귀찮아서 그냥 넘겼었;;)
> 
> githru를 사용하면 이런 꼬인(?) 케이스도 잘 정리해서 보여주는 걸 시나리오에 넣는것도 좋을 것 같네요!

바쁘신 와중 꼼꼼히 확인해 주셔서 감사합니다🥹
실수한 것 같아 신경쓰였는데, 하나의 아이디어로 승화시켜 주시니 신기하기도 하고 재밌네요!! 감사합니다!!😀