test(view): Detail.util.ts tc 추가
githru/githru-vscode-ext pull request #436
Opened 2023-08-30 08:18 UTC by KKanghh

## Related issue
resolve #422 

## Result
<img width="344" alt="스크린샷 2023-08-30 오후 5 13 15" src="https://github.com/githru/githru-vscode-ext/assets/84486674/1cf98dfb-47cc-46fd-b174-8e2bdaf85f1a">

## Work list
Detail.util.ts에 test case 추가
test case 작성하다보니 getSummaryCommitList에서 이상한 점이 있어 수정하였습니다.

## Discussion
처음으로 test case를 만들어보았습니다 :) 개선할 점이 있으시면 피드백 주시면 감사하겠습니다!!

2023-08-30 11:06 UTC, KKanghh commented
@all-contributors please add @KKanghh for code

2023-08-31 02:08 UTC, ytaek commented on packages/view/src/components/Detail/Detail.util.ts
> +  for (let item = arr.length - 1; arr.length >= l ? item > arr.length - 1 - l : item >= 0; item -= 1) {
이부분이 말씀해주신 `이상한 부분` 같은데, 
혹시 어떤 이유로 수정하셨는지 설명해주실 수 있으실까요?

2023-08-31 02:37 UTC, KKanghh commented on packages/view/src/components/Detail/Detail.util.ts
> +  for (let item = arr.length - 1; arr.length >= l ? item > arr.length - 1 - l : item >= 0; item -= 1) {
메소드가 commitNode[] 중 상위 l개를 잘라서 return 해주는 메소드 같은데, 제가 수정한 부분이 5로 고정되어 있었습니다.
지금은 호출할 때 항상 l값을 5로 넣어서 호출해서 에러가 발생하지 않는데, l > arr.length >= 5 이런 식으로 호출을 하게되면 음의 index에 접근하게 됩니다!!
arr의 길이가 l보다 크거나 같을 때는 상위 l개를 잘라서 return하고, arr의 길이가 l보다 작을 때는 arr의 길이 만큼 return 할 수 있게 하는게 원래 의도가 아닐까 싶어서 그렇게 수정하였습니다.

2023-09-03 05:16 UTC, ytaek commented on packages/view/src/components/Detail/Detail.util.ts
> +  for (let item = arr.length - 1; arr.length >= l ? item > arr.length - 1 - l : item >= 0; item -= 1) {
이 코드 혹시, 
detail list가 길어질 경우 5개만 보이게 한다음, read more 처리하는 부분하고 관련이 있는게 아닌지 확인이 필요할 것 같습니다.
@KKanghh 님, 확인 부탁드릴께요!!

<img width="929" alt="image" src="https://github.com/githru/githru-vscode-ext/assets/24404665/c90a02e3-d0e6-4b91-81c9-66e7eed4ef4b">

혹시 그게 맞다면, 저 5라는 숫자는 다른 숫자 상수로 빼서 이름을 별도로 지어야 할 것 같군요!

2023-09-03 05:25 UTC, 2taesung commented on packages/view/src/components/Detail/Detail.util.test.ts
> +  expect(result2[0].commit.id).toBe(fakeCommitNodeListInCluster[2].commit.id);
사실 이 두 가지 테스트 코드케이스가 동일함으로 하나만 있어도 될 것 같습니다! 똑같은 로직이 두번 테스트할 필요는 없을 것 같아요! 

똑같은 테스트 로직 케이스가 두개가 있으면 좋은 점은 없고 유지보수상, 가독성상, 프로젝트 덩어리상 미미하지만 안좋은 점이 있는 것 같습니다!

또한, 이 때문에 변수명을 의미 없이 result1, result2 가 되었는데 하나가 되면서 result 로 처리하면 좋을 것 같아요!

2023-09-03 05:26 UTC, KKanghh commented on packages/view/src/components/Detail/Detail.util.ts
> +  for (let item = arr.length - 1; arr.length >= l ? item > arr.length - 1 - l : item >= 0; item -= 1) {
> 이 코드 혹시, 
> 
> detail list가 길어질 경우 5개만 보이게 한다음, read more 처리하는 부분하고 관련이 있는게 아닌지 확인이 필요할 것 같습니다.
> 
> @KKanghh 님, 확인 부탁드릴께요!!
> 
> 
> 
> <img width="929" alt="image" src="https://github.com/githru/githru-vscode-ext/assets/24404665/c90a02e3-d0e6-4b91-81c9-66e7eed4ef4b">
> 
> 
> 
> 혹시 그게 맞다면, 저 5라는 숫자는 다른 숫자 상수로 빼서 이름을 별도로 지어야 할 것 같군요!


해당 부분의 코드가 맞습니다!! 그렇게 수정하도록 하겠습니다!

2023-09-07 04:42 UTC, ytaek requested changes
리뷰 검토 부탁드립니다~
(request changes 한 번 해봤습니다. 평소에 안써봐서 써보고 싶었어요... ^^;)

2023-09-07 04:42 UTC, ytaek commented on packages/view/src/components/Detail/Detail.hook.tsx
> +  const list = getSummaryCommitList(commitNodeListInCluster);
5를 별도의 변수로 뺀 것은 매우 좋은것 같습니다만,
`getSummaryCommitList` 의 parameter에서 제외를 하게 되면,

getSummaryCommitList 함수 자체가 input으로 들어오는 parameter외에
외부 전역 변수 `SUMMARY_COMMIT_LIST_PREVIEW_LENGTH` 에도 의존성을 가져서
side effect이 발생할 수 있을 것 같습니다.

가급적이면 순수함수의 느낌으로 짜는 것이 좋을 것 같습니다 : )

2023-09-07 05:26 UTC, KKanghh commented on packages/view/src/components/Detail/Detail.hook.tsx
> +  const list = getSummaryCommitList(commitNodeListInCluster);
> 5를 별도의 변수로 뺀 것은 매우 좋은것 같습니다만, `getSummaryCommitList` 의 parameter에서 제외를 하게 되면,
> 
> getSummaryCommitList 함수 자체가 input으로 들어오는 parameter외에 외부 전역 변수 `SUMMARY_COMMIT_LIST_PREVIEW_LENGTH` 에도 의존성을 가져서 side effect이 발생할 수 있을 것 같습니다.
> 
> 가급적이면 순수함수의 느낌으로 짜는 것이 좋을 것 같습니다 : )

말씀하진 점 참고하여 상수가 함수 내부에 위치하도록 변경하였습니다!

2023-09-07 06:04 UTC, ytaek approved these changes
LGTM!

2023-09-07 06:04 UTC, ytaek commented on packages/view/src/components/Detail/Detail.hook.tsx
> +  const list = getSummaryCommitList(commitNodeListInCluster);
> 말씀하진 점 참고하여 상수가 함수 내부에 위치하도록 변경하였습니다!

아, 내부에 위치해도 괜찮긴 한데, 해당 경우는 전역변수 느낌으로 해도 괜찮을 것 같아요.
(5라는 숫자를 다른 곳에서 활용할 수도 있으니까요)

일단은 진행하고, 추후에 또 변경해봅시다!

2023-09-08 14:09 UTC, kimdonggu42 approved these changes
test case 추가 좋습니다~

2023-09-09 01:37 UTC, merged