feat(view): FakeIDEAdapter.ts 임의 수정
githru/githru-vscode-ext pull request #490
Opened 2023-09-23 07:13 UTC by KyuTae98

## Related issue

## Result
view에서 npm start 후 개발자도구를 키면 오류가 나와 FakeIDEAdapter.ts를 임의로 고쳤습니다.
## Work list

## Discussion

2023-09-23 09:49 UTC, 2taesung approved these changes
LGTM~!
command가 들어오는 쪽(engine일 거 같은데...)에서 달라진 지점을 한번 체크하고 넘어가면 좋을 것 같긴합니다! 이전에는 문제 없다가 생긴걸 보니 ...

2023-09-24 14:58 UTC, ytaek requested changes
에러 잘 확인하신 것 같습니다! 👍 
좀 더 근원적인 해결책을 suggestion했으니 확인부탁드립니다.

2023-09-24 14:58 UTC, ytaek commented on packages/view/src/ide/FakeIDEAdapter.ts
>          case "fetchAnalyzedData":
살펴보니, onReceiveMessage가 githru가 보낸 것 뿐만이 아니라 모든 종류의 이벤트들을 다 받는데,
그 과정에서 payload 데이터 형태를 인식하는 부분이 달라져서 일어나는 일입니다.

githru command일때만 payload를 읽게 하면 될 것 같습니다.

```suggestion
            const { command, payload } = responseMessage;

      switch (command) {
        case "fetchAnalyzedData":
          return events.handleChangeAnalyzedData(payload ? JSON.parse(payload) : undefined);
        case "fetchBranchList":
          return events.handleChangeBranchList(payload ? JSON.parse(payload) : undefined);
        default:
          console.log("Unknown Message");
      }
```

2023-09-26 11:48 UTC, ss-won approved these changes

2023-09-26 11:48 UTC, ss-won commented on packages/view/src/ide/FakeIDEAdapter.ts
> +            const { command, payload } = responseMessage;
[제안]
```suggestion
            const { command, payload } = responseMessage;
            const payloadData = command && payload ? JSON.parse(payload) : payload;
```

2023-09-26 11:48 UTC, ss-won commented on packages/view/src/ide/FakeIDEAdapter.ts
> +            const { command, payload } = responseMessage;
+ 16 line이랑 17 line 중복인거 같은데 확인해주세요!

2023-09-26 15:06 UTC, KyuTae98 commented on packages/view/src/ide/FakeIDEAdapter.ts
> +            const { command, payload } = responseMessage;
맞아요! conflict해결할때 지울려고 했는데 제안 감사합니다!!!

2023-09-29 07:13 UTC, ytaek commented
build fail나는 것 한번 확인 부탁드려요~

2023-09-29 13:46 UTC, ytaek commented
Node.js CI/build 에러이고, 
https://github.com/githru/githru-vscode-ext/actions/runs/6352422006/job/17255216999?pr=490

<img width="1144" alt="image" src="https://github.com/githru/githru-vscode-ext/assets/24404665/a3fc6ae5-bf20-42a9-a79a-9e78de9f5fe3">

type고치는 쪽에서 난 에러 같아요 (CI 도는데 왜 에러가 들어왔을까요 ㅜ.ㅜ)
해당 부분 수정하시면 됩니다.
(혹은 이후에 제가 올릴 pr에서 수정됐으니 기다리셔도 되고...)

2023-09-29 14:17 UTC, KyuTae98 reviewed
vscode랑 view 타입 정리하는게 들어갔나 보네요,,,ㅠㅠ 멘토님의 pr을 기다리겠습니다!!!

2023-09-29 15:09 UTC, ytaek commented
> vscode랑 view 타입 정리하는게 들어갔나 보네요,,,ㅠㅠ 멘토님의 pr을 기다리겠습니다!!!

PR 올려서 merge 했습니다.

2023-09-30 14:43 UTC, ytaek approved these changes
반영 감사합니다!

2023-09-30 17:18 UTC, merged