[engine] 성능 최적화를 위한 view와의 메시징 방안
githru/githru-vscode-ext pull request #628
Opened 2024-08-09 06:22 UTC by bbanderson

## Related issue
#618
view와 engine 간의 git log 추가 요청을 위한 메시징 로직을 추가하였습니다.
현재 릴리즈되어 있는([v0.6.1](https://github.com/githru/githru-vscode-ext/releases/tag/v0.6.1)) 메인 로직에 영향을 최소화하기 위해 우선 `upstream:main`에서 `feature/618` 브랜치를 따로 추가하여 작업중입니다.
engine 및 view 성능 최적화 모듈의 다른 기능들과 어느정도 병합된 후 main에 머지하는 것이 좋을 것 같아서 이렇게 진행하였고, 성능 최적화를 담당하시는 다른 분들도 우선 여기에 머지해 두는 것이 좋을 것 같은데, 이와 관련하여 의견 주셔도 좋습니다!!

## Result
https://github.com/user-attachments/assets/9b87a4ca-bbef-4c9e-9dd3-92dd3d11d172

## Work list
> 초안 코드 작성의 범위
> - view
>   - 스크롤 대신 단순 버튼 클릭으로 트리거
>   - GlobalDataProvider에서 지금까지 받아온 git log(커밋노드)의 개수를 useState에 저장
>   - IDE Port & Message 요청
> - engine
>   - Message payload 파싱해서 getGitLog 재호출
>   - Message 답장

https://github.com/githru/githru-vscode-ext/issues/618#issuecomment-2273493982

## Discussion
- TODO
  - `<TemporalFilter />`(상단 CLOC, Commit 그래프)는 전체를 보여주도록 `commitDate` & `differenceStatistics`만 따로 전체 처리 가능한지 검토 예정
  - git log 분할 처리를 위한 파라미터 추가
  - CSM 노드 재생성 연구 (@BeA-Pro 님께서 담당해주고 계시며, 함께 연구해도 좋을 것 같습니다! 🙌)
- 해당 이슈를 해결하면서 생각난 제안 사항
  - 초기 실행 시 몇 개의 로그를 불러올지 추후 정하면 좋겠습니다.
    - 평균 N개의 CSM 노드를 만들었을 때 초기 로딩되는 시간을 역추산하여, 특정 개수의 로그만 처음에 받도록 상수를 하드코딩하거나,
    - 설정 탭이나 view의 Select 등에서 유저가 고를 수 있도록 하거나
    - etc.
  - 다음과 같이 패키지(vscode&engine&view) 공통으로 쓰이는 상수 또는 함수를 전역 관리하는 것도 좋을 것 같습니다. (`packages/utils`처럼 새로 만들어도 되며, 현재는 임시로 `packages/analysis-engine/utils`에 만들어두었습니다)
    - 메시지 커맨드명(ex. fetchAnalyzedData, refresh, updatePrimaryColor, fetchMoreGitLog, ...)
    - 이번 이슈에서 새로 만든 `getPayloadParam` 함수
- cc. @novice1993 @BeA-Pro @yoouyeon @seungineer @Sang-minKIM

2024-08-09 06:46 UTC, ytaek requested changes
리뷰 남겼습니다!

- feature branch로 별도로 한 것은 괜찮은 아이디어 같습니다.
- PR을 더 쪼개서 올려주시면 좋을 것 같습니다. 리뷰하기가 빡씨긴 합니다 ㅜ.ㅜ 현재같은 경우라면 아래처럼 나눌 수 있을 것 같아요.
  - engine에서 처리하는 부분 + test해볼 수 있는 jest tc (아... 이 부분은 지금 없는거죠?)
  - view에서 처리하는 부분(+fakeIDE)로 확인
  - vscode에서 처리하는 부분(+VSCodeIDE) + e2e(이건 좀 힘들겠죠? ^^)
- vscode/tsconfig.json에 dependency 설정하는 부분은 수정이 필요할 것 같아서 request changes로 남깁니다.
- 다른 부분들은 어차피 feature branch로 분리한 상황이니, 현재 PR에서 다 처리하지 말고, 다음 PR에서 처리해도 괜찮을 것 같습니다.

제 생각이 다 맞는건 아니니 (당연), 여러가지 피드백들 환영합니다.

2024-08-09 06:46 UTC, ytaek commented on packages/analysis-engine/src/utils/index.ts
> +export * from "./regex";
(사소) 매우 사소합니다만,
파일이나 function등의 naming은 기능적인 면 보다는, 
도메인(비지니스 로직) 관점에서 작명하는게 더 좋을 수도 있을 것 같습니다.

예를 들어 현재 getPayloadParam 이면, 
`regex를 쓰니까 regex util 이라고 부르자` 라기 보다는
`URL을 파싱하는 util` 혹은 `메시징 관련 유틸` 등으로 정리하는게
추후에 더 이해하기 쉽지 않을까? 하는 느낌이 드네요. 

이것도 여러가지 의견이 있을 수 있으니, 다른 의견들도 환영합니다.

2024-08-09 06:46 UTC, ytaek commented on packages/view/src/App.tsx
> +      // TODO : 커맨드명이 패키지 공통으로 쓰이고 있기 때문에, enum 등으로 전역 관리하는 것도 좋을 것 같습니다.
전역 메시지 관리는 필수인 것 같아요!! (제가 안 만들었었군요;;; ㅋㅋ 👿)

2024-08-09 06:46 UTC, ytaek commented on packages/view/src/App.tsx
> +      if (message.command === "fetchMoreGitLog") {
(이것도 위와 비슷 + 사소) 기능상으로 `GitLog`가 맞긴 한데,
해당하는 의미가 Log를 가져오는건지, 아니면 이전 `내용? Context?`들을 가져오는 건지 등을 의미하는 용어로 바꾸는 것도 좋을 것 같습니다.

2024-08-09 06:46 UTC, ytaek commented on packages/view/src/App.tsx
> +        setCurrentGitLogCount((p) => p + +newGitLogCount);
IMHO, 간결한 표현이 좋긴 한데, + + 이 붙어있을 때 조금 헷갈리는 부분도 있을 것 같아서, 괄호를 더해주면 더 좋지 않을까요?

2024-08-09 06:46 UTC, ytaek commented on packages/view/src/context/GlobalDataProvider.tsx
> +  const [currentGitLogCount, setCurrentGitLogCount] = useState<number>(100);
100은 추후에 전역 configuration 등으로 빼면 좋긴 하겠네요.
일단 상수화는 필요해보입니다.

2024-08-09 06:46 UTC, ytaek commented on packages/view/src/hooks/useGlobalData.ts
> +  setCurrentGitLogCount: Dispatch<SetStateAction<number>>;
빨리 상태관리 lib을 적용시켜야겠군요... 뭔가 점점 지저분해지고 있네요 ㅋㅋ

2024-08-09 06:46 UTC, ytaek commented on packages/view/src/ide/FakeIDEAdapter.ts
> +      payload: `offset=${offset}&limit=${limit}`,
(궁금) URL 형식을 취하신 이유가 따로 있을까요?
properties를 바로 JSON.stringify 했어도 괜찮았을 것 같은데

2024-08-09 06:46 UTC, ytaek commented on packages/vscode/src/webview-loader.ts
> +        console.log("view -> engine 메시지 : ", { offset, limit, newGitLogCount });
주석은 그렇다치더라도, console log는 (다국적 사용자를 위해... 거의 없을 것 같지만 ㅜ.ㅜ) 영어로 해주시면 좋을 것 같습니다!

2024-08-09 06:46 UTC, ytaek commented on packages/vscode/tsconfig.json
> +    "rootDirs": ["src", "../analysis-engine"],
이 부분은 좀 수정이 필요하지 않나 싶습니다.
monorepo라서, packages 안의 package들에서 사용하는 lib들을
알아서(?) import 해서(package.json dependencies) 사용하는 거기 때문에
이렇게 직접적으로 link를 해서 사용하는 부분은 제거해야 할 것 같습니다.

2024-08-09 09:12 UTC, seungineer commented
> 현재 릴리즈되어 있는([v0.6.1](https://github.com/githru/githru-vscode-ext/releases/tag/v0.6.1)) 메인 로직에 영향을 최소화하기 위해 우선 upstream:main에서 feature/618 브랜치를 따로 추가하여 작업중입니다.
> engine 및 view 성능 최적화 모듈의 다른 기능들과 어느정도 병합된 후 main에 머지하는 것이 좋을 것 같아서 이렇게 진행하였고, 성능 최적화를 담당하시는 다른 분들도 우선 여기에 머지해 두는 것이 좋을 것 같은데, 이와 관련하여 의견 주셔도 좋습니다!!

`feature/618`에서 작업하는 게 좋을 것 같습니다! 🙌

> 해당 이슈를 해결하면서 생각난 제안 사항
>> - 초기 실행 시 몇 개의 로그를 불러올지 추후 정하면 좋겠습니다

View에서는 어떤 방식으로 렌더링 하느냐에 따라 (Pagination, Infinite scroll, react-virtualized 등) '최소 N개의 CSM 노드는 필요하다'고 의견 드릴 수 있을 것 같습니다!
_(아직 확실히 어떻게 되겠다는 감이 없어서.. Engine 팀에서 몇 개의 로그 단위로 불러올지 정할 때 말씀드릴 수 있도록 하겠습니다. 🫡)_

2024-08-10 06:36 UTC, xxxjinn commented on packages/analysis-engine/src/utils/index.ts
> +export * from "./regex";
저도 말씀에 동의합니다! 함수가 어떤 기능을 하는 지 일일히 주석을 다는 것도 방법(?)이겠지만 효율적이지 못하고 코드가 복잡해 보일 것 같아 좋지 않은 방법인 것 같고, 말씀하신 대로 도메인 관점으로 이름을 짓는 것이 직관적으로 이해하기 쉬울 것 같다고 생각합니담

2024-08-10 06:37 UTC, xxxjinn commented on packages/view/src/App.tsx
> +            로그 더 불러오기 (현재 {currentGitLogCount}개)
혹시 모를(?) 외국인 사용자를 위해 한국어보다는 영어로 text를 작성하는 것은 어떻게 생각하시나요!

2024-08-14 00:08 UTC, bbanderson commented on packages/analysis-engine/src/utils/index.ts
> +export * from "./regex";
좋은 의견 감사합니다~!

2024-08-14 00:12 UTC, bbanderson commented on packages/view/src/App.tsx
> +      if (message.command === "fetchMoreGitLog") {
동의합니다. 기능에만 집중한 감이 있네요. 이 행위가 CSM 가공 시, 기존 것에 덧붙여서 가져오는 것 등이 명확하다면 그에 따라 수정해보겠습니다!

2024-08-14 01:30 UTC, ytaek commented
> * vscode/tsconfig.json에 dependency

해당 부분만 수정하고, 나머지 부분은 다음 PR에서 진행하시면 될 것 같습니다.
(build랑 엮인 부분이라, packaging하거나 할때도 좀 이슈가 있을 것 같아서, 이 부분만 이번 pr에서 수정하고 가면 좋겟습니다!)

2024-08-14 05:11 UTC, bbanderson commented
> > * vscode/tsconfig.json에 dependency
> 
> 해당 부분만 수정하고, 나머지 부분은 다음 PR에서 진행하시면 될 것 같습니다. (build랑 엮인 부분이라, packaging하거나 할때도 좀 이슈가 있을 것 같아서, 이 부분만 이번 pr에서 수정하고 가면 좋겟습니다!)

@ytaek 네~ 말씀 이해했습니다!
우선 저렇게 수정했던 것은, regex.ts의 `getPayloadParams` 로직이 view와 vscode에서 모두 사용되기 때문에, regex.ts를 따로 만들어서 import 시키기 위함이었습니다.
tsconfig.json을 수정하기 전에는 빌드 시 모듈을 찾을 수 없어서 계속 에러가 났었거든요.
해결해보고, 이슈가 또 생기면 공유드리겠습니다!

2024-08-14 05:33 UTC, ytaek commented
> > > * vscode/tsconfig.json에 dependency
> > 
> > 
> > 해당 부분만 수정하고, 나머지 부분은 다음 PR에서 진행하시면 될 것 같습니다. (build랑 엮인 부분이라, packaging하거나 할때도 좀 이슈가 있을 것 같아서, 이 부분만 이번 pr에서 수정하고 가면 좋겟습니다!)
> 
> @ytaek 네~ 말씀 이해했습니다! 우선 저렇게 수정했던 것은, regex.ts의 `getPayloadParams` 로직이 view와 vscode에서 모두 사용되기 때문에, regex.ts를 따로 만들어서 import 시키기 위함이었습니다. tsconfig.json을 수정하기 전에는 빌드 시 모듈을 찾을 수 없어서 계속 에러가 났었거든요. 해결해보고, 이슈가 또 생기면 공유드리겠습니다!

아 view랑 vscode군요. 
그러려면 common library같은 패키지 모듈을 추가로 만들어야할 것 같습니다.
약간 오버스펙 같아서, json같은 표준 프로토콜을 쓰는게 나을 것 같네요 😂

2024-08-14 05:56 UTC, bbanderson commented
> 아 view랑 vscode군요. 그러려면 common library같은 패키지 모듈을 추가로 만들어야할 것 같습니다. 약간 오버스펙 같아서, json같은 표준 프로토콜을 쓰는게 나을 것 같네요 😂

@ytaek
ㅎㅎ 그러게요~ 위의 
> (궁금) URL 형식을 취하신 이유가 따로 있을까요?
properties를 바로 JSON.stringify 했어도 괜찮았을 것 같은데

와 연결되는 이야기같은데요.

처음에는 예를 들어 아래와 같이 확장할까 하다가, 기존의 `const payloadData = payload ? JSON.parse(payload) : undefined;` 코드까지 사이드이펙트를 줄 수 없다보니, 좀 오버스펙으로 빠져버린 것 같습니다.
```
export type IDEMessage<T = string> = {
  command: IDEMessageCommandNames;
  payload?: T;
};
```
다시 생각해보니 JSON.stringify로 통일시켜보면 될 것 같네요~ 또다른 패키지를 현 시점에서 만드는 것은 더 큰 영향을 낳을 것 같네요.
말씀주셔서 감사합니다ㅎㅎ

2024-08-20 02:41 UTC, ytaek commented on packages/vscode/tsconfig.json
> +    "rootDirs": ["src", "../analysis-engine"],
> 이 부분은 좀 수정이 필요하지 않나 싶습니다. monorepo라서, packages 안의 package들에서 사용하는 lib들을 알아서(?) import 해서(package.json dependencies) 사용하는 거기 때문에 이렇게 직접적으로 link를 해서 사용하는 부분은 제거해야 할 것 같습니다.

@bbanderson 님, change request를 남겨서 그런지, 왠지 후속 작업이 없으시군요.. 마상을 입으신거면 죄송합니다 😈 
요 부분이랑 JSON.stringify 수정 부분만 살짝 고쳐서 일단 PR 올려서 넘어가시고,
추가적인건 다음 PR로 진행해보시면 어떨까요? 🛩️

2024-08-20 09:22 UTC, bbanderson commented on packages/vscode/tsconfig.json
> +    "rootDirs": ["src", "../analysis-engine"],
바로 작업하겠습니다

2024-08-22 02:07 UTC, ytaek approved these changes
디테일한 반영 감사합니다!! LGTM!

2024-08-22 02:07 UTC, ytaek commented on packages/view/src/ide/VSCodeIDEAdapter.ts
> +          }
offset 변수에 문제(?)가 있을 경우,
명시적인 시스템 동작이 있던지 하면 좋을 것 같습니다.

추후에 에러처리 관련 수정도 해주시면 감사하겠습니다!

2024-08-22 05:06 UTC, bbanderson commented on packages/view/src/ide/VSCodeIDEAdapter.ts
> +          }
좋습니다~!

2024-08-22 15:02 UTC, bbanderson commented on packages/view/src/App.tsx
> +      console.log("[engine -> view] message : ", { message });
아직은 디버깅 용도로 남겨두었고('Congratulations, your extension "githru" is now active!'와 유사), 추후 삭제해도 될 것 같습니다!

2024-08-22 15:03 UTC, merged