[engine] getCommitRaws 함수 개선
githru/githru-vscode-ext pull request #680
Opened 2024-08-30 02:30 UTC by yoouyeon

## Related issue

closes #675 

## Work list

- `getGitLog` 함수로 불러오는 git log의 포맷을 파싱이 간단한 형태로 변경했습니다.
   
   ```
   // commit별 git log 포맷
   // diffstat을 제외한 각 항목은 `GIT_LOG_SEPARATOR` 로 구분됩니다.
   <COMMIT_SEPARATOR> <hash> <parent hashes> <refs(branches, tags> <author> <committer> <subject(message)>
   <diffstat>
   ```
   참고 : https://git-scm.com/docs/pretty-formats
- 변경한 git log 포맷에 맞게 `getCommitRaws` 의 파싱 방식을 수정했습니다.
- 변경한 git log 포맷에 맞게 `getCommitRaws` 테스트 케이스의 형식을 수정했습니다.
  (prettier에 문제가 있었는지,, 변경사항이 많아졌네요.. 🥲)

## Discussion

vscode 패키지의 `getGitLog`와 engine 패키지의 `getCommitRaws`에서 모두 쓰이는 SEPARATOR 상수를 우선 engine쪽 constant.ts에 선언해두었는데, 괜찮은 방법인지 잘 모르겠습니다,,,
더 좋은 방법이 있다면 코멘트 부탁드립니다! 🙇‍♀️

2024-08-31 06:33 UTC, choisohyun approved these changes
👍 수고하셨습니다!

2024-08-31 06:33 UTC, choisohyun commented on packages/analysis-engine/src/constant.ts
> +export const GIT_LOG_SEPARATOR = "I9M-0XOzvHlYPegVPpzb";
constants에 따로 빼두는 것 너무 좋은 것 같습니다! 👍

2024-08-31 06:33 UTC, choisohyun commented on packages/analysis-engine/src/parser.ts
> +      message: commitData[9],
여기 취향 차이긴 하지만 array destructuring으로 표시도 가능하겠네요!

```
const [id, parentsText, name, email, ......] = commitLines[0].split(GIT_LOG_SEPARATOR);
```

```suggestion
      id,
      parents: parentsText.split(" "),
      branches, // commitData[2] is already split into branches and tags
      tags,
      author: {
        name,
        email,
      },
      ...
```

2024-08-31 06:33 UTC, choisohyun commented on packages/vscode/src/utils/git.util.ts
> +      `--pretty=format:${gitLogFormat}`,
(질문) 이 상수로 빼둔 seperator들은 pretty 속성으로 포맷에 지정해주면 임의로 지정해서 사용할 수 있는 건가요?? 
상수들 값은 어떤 원리로 설정하게 된건지도 궁금하네요!

2024-08-31 07:40 UTC, yoouyeon commented on packages/vscode/src/utils/git.util.ts
> +      `--pretty=format:${gitLogFormat}`,
`COMMIT_SEPARATOR`, `GIT_LOG_SEPARATOR` 값은 git log 출력 값에 특정한 구분자가 있어야 파싱하기가 더 쉬울 것 같아 지정한 것이고 완전 제 마음대로 임의의 값으로 설정한 것입니다..! (저는 랜덤한 문자열을 만들어주는 서비스 서치해서 20자 길이의 문자열 두개 만들어 넣었습니다..ㅎㅎ)
그래서 constant.ts 의 내용을 바꿔서 임의로 지정하기도 가능합니다!

제가 질문해주신 것을 잘 이해한건지 모르겠는데,,,
pretty 속성 값으로 들어가 있는 `gitLogFormat` 역시도 [git log 명령의 format 규칙](https://git-scm.com/docs/pretty-formats)에 맞춰서
저희가 필요한 데이터 값들과 상수로 설정한 seperator들을 조합하기만 한 것이라
이 부분도 getCommitRaws의 파싱 방식이 바뀐다면 얼마든지 변경 가능합니닷

2024-08-31 08:18 UTC, choisohyun commented on packages/vscode/src/utils/git.util.ts
> +      `--pretty=format:${gitLogFormat}`,
아하 그렇군요 랜덤한 문자열로 넣는 것도 정해둔 상수만 쓸 수 있게 하는 거라 좋은 것 같네요! 
답변주신 내용이 질문한 내용에 대한 게 맞습니다! 답변 감사합니다! 👍👍👍

2024-08-31 13:35 UTC, ytaek requested changes
코드웍이 엄청나네요!!!  👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍 

보통은 제가 '이번에 일단 넣고 점진적으로 보완해주세요!' 라고 하는데, 
이번 건 나름대로 중대 변경사항 부분이라, 일단 request changes로 걸어놓습니다.
(코드에 이상이 있다!라기보다는, 조금 더 강건성을 확인하기 위함이라고 생각해주시면 감사하겠습니다 😃)

- 우선 PR detail 부분에 기존 log가 어떻게 변경되었는지를 as-is, to-be 형식으로 예시를 보여주시면 좋을 것 같습니다. 단순히 format 만 보고 판단하기에는 조금 정보가 부족합니다.
- "왜" 변경되었는지에 대한 의도에 대한 설명이 빠진 것 같습니다. 경량화를 위함인지, 다른 기능적인 면의 추가 때문인지에 대한 설명이 필요할 것 같습니다.
  (issue에 `파싱하기 좋은 포맷으로 바꾸고, 파싱 과정을 덜 복잡하게`라고 되어 있긴 한데, 이게 단순히 복잡성 때문에 바꾸는 건지, 아니면 성능을 올리기 위해서인지 설명도 필요할 것 같습니다)
- parser부분의 복잡성은 확실히 좋아진 건 맞습니다만, log로 받아오는 데이터의 이해는 기존이 더 편할 수도 잇을 것 같습니다. 지금은 난수같은 임의의 separator가 더 추가되었기도 하구요.
- separator부분은 newline(\n) 정도면 충분할 것 같은데 (log message를 제일 아래에 넣는다면), 이 부분은 실제 log의 format을 보고 판단하면 좋을 것 같구요.

- 그리고, 현재 잘 돌아가는(?) legacy코드의 변경사항이 크다면, 사실 test code도 더 만들어줘야 할 수도 있습니다.

2024-08-31 13:35 UTC, ytaek commented on packages/analysis-engine/src/parser.spec.ts
> +  const expectedTags = [[], [], ["v1.0.0"], ["v2.0.0"], ["v2.0.0", "v1.4"]];
이 부분은 prettier가 자동으로 변경한 부분일까요?
개인적으로는 기존에 line by line으로 구분해놓은 것이 더 가독성이 좋은 것 같습니다 😸

2024-08-31 13:35 UTC, ytaek commented on packages/analysis-engine/src/parser.spec.ts
> +    message: testCommitMessage,
test를 확인하는 value들을 변수 처리한 별도의 이유가 있을까요?
가독성도 그렇고, 보통 test할 때 확인하는 값들은 연산을 거친 값이 아니라,
본연의 값(?)을 사용하는게 더 좋을 수 있습니다.  (반복되어서 사용되는 경우가 아니라면)

살짝 사례가 다르게 보일 수 있지만, 아래 reference 추가합니다.
https://learn.microsoft.com/ko-kr/dotnet/core/testing/unit-testing-best-practices#avoid-logic-in-tests

2024-08-31 13:35 UTC, ytaek commented on packages/analysis-engine/src/parser.spec.ts
> +  );
이 줄도 아래 117 line 과 유사합니다.

2024-08-31 13:47 UTC, ytaek commented on packages/analysis-engine/src/parser.ts
> +        email: commitData[7],
혹시 author 나 committer가 복수개가 들어가는 case도 고려가 되었을까요?

2024-08-31 13:47 UTC, ytaek commented on packages/vscode/src/utils/git.util.ts
> +      ].join(GIT_LOG_SEPARATOR);
작성해주신 코드를 보고, constant 파일이 새로 생성되는 걸 보니, 
기존에 vscode, engine에서 parser의 위치가 참 애매하다는 생각이 드네요.

뭔가 엔진은 구조화(json?)된 commitRaw만 받아서 처리(분석)하는 놈이고,
git log를 뽑고, 파싱해서 commitRaw형태로 만들어 주는 부분은 엔진이 몰라도 되지 않나? 하는 생각이 문득 들긴 합니다 ❓_❓

아니면, 아예 gitLog를 어떻게 찍어야 한다!! 라는 위 argument 정보들을 아예 engine이 가지고 있고, 그걸 vscode가 불러서 써도 될 것 같구요. 

architecture에 명확한 답이 없을 수도 있는거라, 이 부분은 한번 논의를 해봐도 괜찮을 것 같군요 : )

2024-08-31 13:47 UTC, ytaek commented on packages/analysis-engine/src/constant.ts
> +export const GIT_LOG_SEPARATOR = "I9M-0XOzvHlYPegVPpzb";
개인적으로는, 요런 매직 코드 같은게 없으면 좋을 것 같긴 합니다.
아래에 적었듯이 new line 정도로 하면 충분할 것 같긴 한데요. ㅎㅎ 찍히는 format 을 봐야겠네요.

parser와 git util이 해당 정보를 동시에 가지고 있어야 하므로, 공통 변수로 뺀 건 좋은 선택인 것 같습니다 👍
단, 아래 parser/logger 위치에 대해 적어놨듯이, 이게 어디로 붙어야 하느냐.. 는 좀 더 고민이 필요할 것 같긴 하구요.

2024-08-31 13:52 UTC, ytaek commented on packages/analysis-engine/src/parser.spec.ts
> -CommitDate: Sun Sep 4 20:17:59 2022 +0900
지금 보니 혹시 이 부분에 대한 재사용 때문에 변수를 만들었다면, 
이 부분만 떼서 변수화 시킨 건 괜찮은데, 
해당 값을 다른 변수들을 분해해서 재사용하는거라면, 기존의 코드들이 테스트 코드적으로는 더 나은 부분이 될 수도 있습니다.

2024-08-31 16:07 UTC, yoouyeon commented on packages/analysis-engine/src/parser.spec.ts
> +  );
테스트 코드 연산 관련한 코멘트 이쪽에 한번에 남깁니다!

테스트 코드 작성은 처음이다보니 기존 코드를 좀 참고했었는데, `expectedBranches` 같은 배열을 만들어두고 조합해서 `expectedResult` 를 만드는 부분을 보고 test 값도 배열을 만들어두고 조합해서 만드는 방식을 썼던 것 같습니다 😅
테스트 input 자체가 특정 값들을 seperator로 join해서 만드는 것이다보니 자연스럽게 연산해서 값을 만들기도 했던 것 같구요.

그리고 117라인에 코멘트 달아주신 test value들을 변수로 처리한 이유는 137라인에 달아주신 것처럼 재사용하기 위한 목적이었고, 위에서 말씀드렸던 test 데이터를 만들기 위해서 배열을 만들어 둔 김에 쓰면 되겠다라는 생각에서 쓴 것입니다 😅

제가 테스트코드에 대한 이해가 부족했네요..... 말씀해주신 것처럼 연산 대신 값을 사용하는 쪽으로 수정해보겠습니다 ㅎㅎ

2024-08-31 16:08 UTC, yoouyeon commented on packages/analysis-engine/src/parser.spec.ts
> +  const expectedTags = [[], [], ["v1.0.0"], ["v2.0.0"], ["v2.0.0", "v1.4"]];
네.. 개인적으로도 line by line으로 구분하는 쪽을 좀 더 좋아하는데 🥲 prettier 적용으로 인해 변경된 부분입니다..!

2024-08-31 16:11 UTC, yoouyeon commented on packages/analysis-engine/src/parser.ts
> +        email: commitData[7],
아니요! author나 committer가 복수인 case는 아직 고려하지 않았습니다.
CommitRaw타입을 보니 author와 committer가 하나씩만 들어가는 것 같은데,
author나 committer가 복수인 case도 있나요..??

2024-09-02 07:27 UTC, ytaek commented on packages/analysis-engine/src/parser.spec.ts
> +  const expectedTags = [[], [], ["v1.0.0"], ["v2.0.0"], ["v2.0.0", "v1.4"]];
저는 그래서 prettier 옵션을 최대한 헐렁하게 해놓고 쓰긴 합니다 😸

2024-09-02 07:30 UTC, ytaek commented on packages/analysis-engine/src/parser.ts
> +        email: commitData[7],
넵 복수 케이스가 있고, 제가 기억이 가물가물해서 100% 확신할 수는 없지만, 기존 코드가 아마도 해당 부분을 다루고 있는 걸로 판단됩니다.
기존 코드에는 이런 부분이 있긴 한데요 (GitUser List를 인자로 받는). 로직을 다 본건 아니라, 확실하지 않습니다 ^^;;

`function getNameAndEmail(category: GitUser[], preParsedInfo: string) {
  category.push({
    name: preParsedInfo.split(": ")[1].split("<")[0].trim(),
    email: preParsedInfo.split(": ")[1].split("<")[1].split(">")[0].trim(),
  });
}`

아무튼, git 자체에서 author, committer가 공동으로 들어가는 케이스가 있는 건 맞습니다!

2024-09-02 07:39 UTC, ytaek commented
해당 PR이 뒷 마일스톤으로 미뤄졌군요 ㅜ.ㅜ

미룬 김에 아래부분들 좀 고려해주시면 좋겠습니다 (@yoouyeon)
- 일단 테스트/검증이 좀 더 필요한 부분이라, 해당 PR을 새로운 branch로 던지시는걸 추천드립니다. feat/675 나 feat/parser 등 원하시는 걸루요.
- 새로운 branch에서 검증이 끝난 뒤에 main 으로 다시 push 날리면 될 것 같습니다.
- 추가(혹은 정리안된) 이슈들은 다 이슈로 등록해주시고, 하나씩 해결하면 좋을 것 같습니다.

2024-09-03 04:20 UTC, yoouyeon commented on packages/analysis-engine/src/parser.ts
> +        email: commitData[7],
아하 제가 지금가지 이해한 것으로는 기존 코드에서도 `Author`와 `Commit`를 커밋당 하나만을 저장하는 것으로 알고 있습니다..!
https://github.com/githru/githru-vscode-ext/blob/9ac07152c89532e4a9f53c263317b32e1872bb9c/packages/analysis-engine/src/types/CommitRaw.ts#L16-L34
위에 함께 올려주신 getNameAndEmail 함수의 GitUser[]도 각 커밋에 해당하는 GitUser 하나씩을 가지고 있고 추후 JSON 타입으로 변환하기 위해서 쓰는 배열이라고 이해했구요 🤔

하지만 말씀해주신대로 git 자체에 author, committer가 공동으로 들어가는 케이스가 있다면 기존 코드와 상관 없이 처리되야 하는 것이 맞기에,,, author, committer가 공동으로 들어가는 케이스가 어떤 경우에 어떤 형태로 만들어지는지 좀 더 조사해 보고 해당 케이스도 테스트케이스에 추가해보겠습니다 ㅎㅎ

2024-09-03 04:23 UTC, yoouyeon commented
넵 해당 PR은 우선 feature/675 브랜치에 머지하고, 리뷰받은 내용들 하나씩 해결해서 따로 PR 올리도록 하겠습니다 💪

2024-09-03 04:24 UTC, ytaek commented on packages/analysis-engine/src/parser.ts
> +        email: commitData[7],
> 

아. 기존도 처리가 안되는 코드였나요?  (제가 githru original ver. 도 있어서 헷갈릴 수 있습니다 ^^;;;)
기존도 안되는게 맞다면 일단 해당 건은 이슈로만 등록하시지요 ㅎㅎ

일단 해당 PR은 이전 comment 달아놓은대로 진행해주시면 좋을 것 같습니다!!
(이번 milestone에 못 넣는게 좀 아쉽긴 하군요 😢)

```
해당 PR이 뒷 마일스톤으로 미뤄졌군요 ㅜ.ㅜ

미룬 김에 아래부분들 좀 고려해주시면 좋겠습니다 (@yoouyeon)

일단 테스트/검증이 좀 더 필요한 부분이라, 해당 PR을 새로운 branch로 던지시는걸 추천드립니다. feat/675 나 feat/parser 등 원하시는 걸루요.
새로운 branch에서 검증이 끝난 뒤에 main 으로 다시 push 날리면 될 것 같습니다.
추가(혹은 정리안된) 이슈들은 다 이슈로 등록해주시고, 하나씩 해결하면 좋을 것 같습니다.
```

2024-09-03 04:25 UTC, merged