[view] debounce, throttle 테스트 코드 작성
githru/githru-vscode-ext pull request #761
Opened 2024-10-06 12:21 UTC by shgusgh12

## Related issue

## Result
<img width="381" alt="스크린샷 2024-10-06 오후 9 13 31" src="https://github.com/user-attachments/assets/7938dd0d-469d-43d7-89a7-751e0c549038">
- debounce 테스트 결과
<img width="386" alt="스크린샷 2024-10-06 오후 9 13 44" src="https://github.com/user-attachments/assets/a28d2400-3bd4-4313-bfae-d8b013335076">
- throttle 테스트 결과

## Work list
- `utils` 폴더 내부의 두 함수 테스트를 진행했습니다. 
- 각각 debounce, throttle이 잘 작동하는지 timer로 테스트 했습니다.
- 추가로 default delay 값에 대한 부분도 테스트 했습니다.
## Discussion
- 처음 테스트 코드를 작성해봐서 혹시 부족한 점이 있다면 편하게 말씀해주시면 감사하겠습니다!!

2024-10-07 07:14 UTC, xxxjinn commented on packages/view/src/utils/debounce.test.ts
> +  it("check debounce", () => {
개인적으로 딱 요 부분만 봐서는 무엇을 체크한다는 의미인지 쉽게 알기 어려운 것 같다고 느껴서 조금 더 설명을 붙여주시는 것에 대해 어떻게 생각하시는지 궁금합니다.!!

2024-10-07 07:15 UTC, xxxjinn commented on packages/view/src/utils/throttle.test.ts
> +  it("check throttle", () => {
해당 부분도 debounce에 남긴 리뷰와 같은 의견이 궁금합니다!

2024-10-07 07:16 UTC, xxxjinn approved these changes
저는 이 함수들은 테스트 할 생각을 못했었는데 너무 좋은 것 같아요!!!✨✨✨

2024-10-07 07:18 UTC, xxxjinn commented
다른 util 함수를 test하는 파일들은 ex) AuthorBarChart.util.test.ts로 되어있어서 이런 식으로 파일명을 통일하면 좋을 것 같은데 다른분들은 어떻게 생각하시나요?! 애초에 utils 폴더 안에서 test를 하는거라 굳이 util을 붙이지 않아도 될 것 같다는 생각도 들고,,

2024-10-07 07:39 UTC, lxxmnmn commented
> 다른 util 함수를 test하는 파일들은 ex) AuthorBarChart.util.test.ts로 되어있어서 이런 식으로 파일명을 통일하면 좋을 것 같은데 다른분들은 어떻게 생각하시나요?!

[CONTRIBUTING.md](https://github.com/githru/githru-vscode-ext/blob/main/packages/view/CONTRIBUTING.md)에는 `*.spec.ts` 형태의 파일명을 사용한다고 되어있으니 `debounce.spec.ts`와 같이 변경하면 어떨까요???

2024-10-07 08:54 UTC, ytaek requested changes
현재 githru view에 구현된 기능들에 대한 Test Case가 있으면 좋을 것 같습니다.
지금 test된 것들은 react component들에 대한 테스트인 것 같네요!

2024-10-07 09:06 UTC, ytaek approved these changes
Timer 관련 TC는 거의 못 봤었는데, 재밌는 구경했습니다.
LGGGGGGTM!!!

2024-10-07 09:06 UTC, ytaek commented on packages/view/src/utils/debounce.test.ts
> +  it("check debounce", () => {
@xxxjinn 님 말대로, 조금 더 자세한 설명이 있으면 좋겠습니다.
(tc 이름만 보고 외부 lib에 대한 tc 인줄 착각했습니다 ㅜ.)

2024-10-07 09:06 UTC, ytaek commented on packages/view/src/utils/debounce.test.ts
> +    jest.advanceTimersByTime(999);
좋은 것 배워갑니다!!! 👍

2024-10-10 14:41 UTC, merged

2024-10-10 14:42 UTC, shgusgh12 commented on packages/view/src/utils/debounce.test.ts
> +  it("check debounce", () => {
아 그렇네요... 좀 더 자세하게 수정하겠습니다!!