[engine] feature/712 브랜치에서 작업한 내용을 main 브랜치에 반영
githru/githru-vscode-ext pull request #766
Opened 2024-10-07 15:20 UTC by BeA-Pro

## Related issue
- #712

## Result
멀티 쓰레드 기법을 활용하여 깃 로그를 받아올 때의 속도를 약 30% 향상시켰습니다.

2024-10-10 04:42 UTC, ytaek requested changes
음. 지금 @yoouyeon 님이 계속 update 하고 있는 gitlog parsing 부분이 들어간 것 같은데,
해당 부분은 아직 작업중인 걸로 알고 있는데 아닐까요?

https://github.com/githru/githru-vscode-ext/pull/753#issuecomment-2395391676

git log parsing 부분은 완료가 되면 가져오면 좋을 것 같고,
우선은 @BeA-Pro 님이 작업해주신 부분만 따로 merge 되는게 좋아보입니다. ㅜ.ㅜ

이미 merge 를 다 하신 것 같아서 죄송하지만, log parser 부분 완료가 되어야 master에 같이 머지되는게 맞는 것 같습니다.

혹시 다른 의견 or 내부적으로 논의하신 내용들이 있다면 말씀 부탁드리겠습니다!

2024-10-10 04:42 UTC, ytaek commented on packages/vscode/src/utils/git.util.ts
> +            resolve(commitCount); // 숫자를 반환
한글 주석은 영어로 변경하거나,
필요없다면 삭제하는게 좋을 것 같습니다!

2024-10-10 04:42 UTC, ytaek commented on packages/vscode/src/utils/git.util.ts
> +}
? indentation 이 뭔가 안 맞는 느낌이네용?

2024-10-10 04:42 UTC, ytaek commented on packages/vscode/src/utils/git.util.ts
> +    console.log('__dirname:', __dirname);
정리하는 김에 console log도 정리해주면 좋을 것 같습니다.
필요한 것 or 런타임 디버깅에 유용한건 놔두고(혹은 부가 설명을 더 넣고), 나머지는 삭제하면 좋겠습니다

2024-11-09 02:27 UTC, ytaek approved these changes
고생 많으셨습니다. githru역사상 가장 묵혀(?)있었던 PR 같군요 👍 
LGTM!

2024-11-09 02:27 UTC, ytaek commented on packages/vscode/src/extension.ts
> +  fetchGitLogInParallel,
unused는 추후에 삭제 해주시면 좋겠습니다!

2024-11-09 02:27 UTC, ytaek commented on packages/vscode/src/utils/git.util.ts
> +export async function getLogCount(gitPath: string, currentWorkspacePath: string): Promise<number> {
드뎌 메인으로 들어오는군요 : )

2024-11-09 06:43 UTC, seungineer approved these changes
크.. 더 빨라진 githru!
LGTM! 🚀🚀🚀🚀

2024-11-09 06:43 UTC, seungineer commented on packages/vscode/src/utils/git.util.ts
> +  }
수 많은 테스트로 도출한 최적의 파라미터 값! 👍👍👍👍

2024-11-09 06:43 UTC, seungineer commented on packages/vscode/webpack.config.js
> +        worker: "./src/utils/git.worker.ts"
여기서 `worker`가 추가되는군요 😁

2024-11-09 07:34 UTC, BeA-Pro commented on packages/vscode/src/extension.ts
> +  fetchGitLogInParallel,
넵!

2024-11-09 07:34 UTC, merged